name: cat_dog
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 2.1.1+1
versionCode: 28

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: 
    git:
      url: git://github.com/flutter/plugins
      path: packages/url_launcher
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  intl: "^0.15.2"
  cupertino_icons: ^0.1.2
  redux: ^3.0.0
  flutter_redux: ^0.5.2
  redux_logging: ^0.3.0
  redux_thunk: ^0.2.1
  redux_persist_flutter: ^0.8.0
  redux_persist: ^0.8.0
  http: ^0.12.0
  html: ^0.13.3+3
  flutter_markdown: ^0.2.0
  flutter_spinkit: ^3.0.0
  carousel_slider: ^1.0.1
  timeago: ^2.0.9
  flutter_staggered_grid_view: ^0.2.4
  share: ^0.5.3
  page_transition: ^1.0.5
  firebase_admob: ^0.7.0
  pull_to_refresh: ^1.1.6
  flutter_parallax: ^0.1.2
  cached_network_image: ^0.5.1
  folding_cell: ^0.1.0
  shimmer: ^0.0.6

dev_dependencies:
  flutter_launcher_icons: ^0.7.0

flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/store/store-3.png"


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/images/login.jpg
  - assets/images/tick.png
  - assets/images/xahoi.jpg
  - assets/images/thegioi.jpg
  - assets/images/vanhoa.jpg
  - assets/images/kinhte.jpg
  - assets/images/giaoduc.jpg
  - assets/images/thethao.jpg
  - assets/images/giaitri.jpg
  - assets/images/congnghe.jpg
  - assets/images/khoahoc.jpg
  - assets/images/tinhot.png
  - assets/images/latest.jpg
  - assets/images/zing.png
  - assets/images/vov.jpg
  - assets/images/thanhnien.jpg
  - assets/images/laodong.jpg
  - assets/images/vietnamplus.jpg
  - assets/images/vietnamnet.png
  - assets/images/vtc.png
  - assets/images/saostart.jpg
  - assets/images/vnmedia.png
  - assets/images/ictnews.png
  - assets/images/tienphong.png
  - assets/images/kienthuc.jpeg
  - assets/videoplayer.jpg
  - assets/images/petrotimes.png
  - assets/images/chinhphu.jpg
  - assets/images/phapluat.png
  - assets/store/icon.png
  - assets/images/banner-1.png
  - assets/images/banner-2.png
  - assets/images/banner-3.png
  - assets/images/noimage-reading.jpg
  - assets/images/noimage.jpg
  - assets/images/swipeleft.png
  - assets/images/swiperight.png
  - assets/images/lamdep.jpg
  - assets/images/kinhdoanh.jpg
  - assets/images/honnhan.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
    - family: Tusj
      fonts:
        - asset: assets/fonts/FFF_Tusj.ttf
    - family: Circle
      fonts:
        - asset: assets/fonts/circle.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
